const data = [
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sollicitudin sollicitudin sagittis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec libero eros, finibus elementum venenatis et, aliquam at diam. Curabitur lectus velit, rutrum eget ultrices non, faucibus ac dolor. Sed venenatis dignissim efficitur. Curabitur rutrum nunc non ante mattis, id porta metus ullamcorper. Aliquam velit ipsum, varius sit amet dignissim quis, tristique non dui. Aliquam dignissim egestas facilisis. Nullam quis cursus enim. Aenean dui nisl, faucibus sed dui ac, vehicula aliquam erat. Nulla sodales est velit, ac congue metus mattis et. Sed et tellus sit amet felis elementum volutpat sit amet nec sem. In eget nulla ligula. Maecenas non diam ut metus varius convallis. Donec sed nunc eget sapien ullamcorper condimentum at non neque. Etiam sapien neque, consectetur in dolor in, tempor sagittis sem.',

'Fusce pretium, risus consectetur vehicula pharetra, nisl purus eleifend eros, in gravida risus lectus a nisi. Mauris ut scelerisque libero. Quisque sem est, condimentum non nibh et, pulvinar consectetur quam. Nulla rutrum arcu efficitur leo gravida, nec tristique erat convallis. Donec luctus imperdiet dignissim. Aenean lectus odio, luctus et leo in, sodales hendrerit mauris. Nulla facilisi. Morbi convallis sollicitudin dapibus. Fusce non luctus ante.',

'Suspendisse ut feugiat odio, in ullamcorper nulla. Quisque vestibulum quam ut feugiat finibus. Ut aliquet sapien ut aliquam vulputate. Phasellus sed nisl tempus, rhoncus lacus vitae, accumsan ipsum. Ut aliquam vulputate odio a scelerisque. Cras volutpat risus egestas neque cursus, eget sodales velit condimentum. Suspendisse sit amet sollicitudin nisi. Maecenas vel dictum augue. In sit amet tempor est. Donec aliquam scelerisque nulla, vel laoreet elit pellentesque id. Fusce elementum turpis a sollicitudin porta. Fusce erat nisi, sodales lobortis felis non, ornare tempor erat. Sed egestas est nec placerat dignissim. In dapibus est id blandit hendrerit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras id velit tellus.',

'Phasellus scelerisque feugiat porttitor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam eleifend massa neque. Morbi in tellus a sapien malesuada bibendum. Fusce eu enim fermentum, elementum urna sit amet, tempor ante. Donec condimentum, turpis vel volutpat efficitur, metus urna auctor ante, eget sollicitudin lacus ante a massa. Nunc vitae est quis urna commodo rutrum. Pellentesque vitae nunc eu turpis aliquet eleifend. Mauris tempor tortor tempus libero ullamcorper, ac faucibus lorem posuere. Aliquam ac congue neque. Morbi fringilla libero ut sodales tempor. Phasellus ullamcorper, neque consectetur ultrices porta, metus mauris feugiat quam, id interdum orci tortor ac nisl. Mauris rutrum ante id laoreet sodales.',

'Nam vitae leo at mi egestas maximus. Phasellus nec pulvinar diam. Cras vel ullamcorper sem. Nullam viverra purus sit amet urna cursus, sit amet ornare lectus egestas. Etiam consequat, velit a tempus tincidunt, ex magna placerat nibh, eget finibus nunc turpis non est. In porttitor vitae urna vel suscipit. Ut vel volutpat ligula. Morbi in tincidunt ante, id ullamcorper purus. Curabitur sed ipsum non ex tempus tempus.',
]

export default data;
